### ISSUE TITLE
Waybar custom wallpaper random setter?

### ISSUE THREAD

**Issue by thepenguinthatwants** [cking/dotfiles#1]
Hi!

Out of all the waybars customications that I've found yours seems to be best.

I tried to use your custom module. But seems like it didn't work at least on my part. Using arch and downloaded xdg-user-dirs etc.      	

`on-click": "env XDG_CURRENT_DESKTOP=sway setrandom $(xdg-user-dir PICTURES)/Wallpaper"
`
clicking on the icon I get an icon flashing on the middle of desktop but no wallpapers changes. Does it need some extra packages or something?

**Comment by cking** [comment]
The wallpapers are stored in `$home/Pictures/Wallpaper`
Just save some in that folder.
Also, do you have the required package installed? (its wallutils from AUR)
